services:
  husn-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: husn-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app/backend
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host" # Essential for Scapy to see real traffic if needed
    restart: always

  husn-frontend:
    image: node:20-alpine
    container_name: husn-frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - husn-backend
    restart: always
